"""empty message

Revision ID: 0317a2913553
Revises: 
Create Date: 2020-05-03 17:30:38.891576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0317a2913553'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluations')
    op.add_column('matches', sa.Column('activity_index', sa.Integer(), nullable=True))
    op.drop_constraint('matches_activitty_fkey', 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'activities', ['activity_index'], ['index'])
    op.drop_column('matches', 'activitty')
    op.add_column('users', sa.Column('match_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'match_count')
    op.add_column('matches', sa.Column('activitty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key('matches_activitty_fkey', 'matches', 'activities', ['activitty'], ['index'])
    op.drop_column('matches', 'activity_index')
    op.create_table('evaluations',
    sa.Column('index', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mate_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('satisfaction', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('react_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_index'], ['matches.index'], name='evaluations_match_index_fkey'),
    sa.ForeignKeyConstraint(['mate_index'], ['users.index'], name='evaluations_mate_index_fkey'),
    sa.ForeignKeyConstraint(['user_index'], ['users.index'], name='evaluations_user_index_fkey'),
    sa.PrimaryKeyConstraint('index', name='evaluations_pkey')
    )
    # ### end Alembic commands ###
