"""empty message

Revision ID: 1dccf760ef1a
Revises: a44f07721317
Create Date: 2020-04-30 12:42:33.583231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dccf760ef1a'
down_revision = 'a44f07721317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('match_index', sa.Integer(), nullable=True),
    sa.Column('user_index', sa.Integer(), nullable=True),
    sa.Column('mate_index', sa.Integer(), nullable=True),
    sa.Column('satisfaction', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_index'], ['matches.index'], ),
    sa.ForeignKeyConstraint(['mate_index'], ['users.index'], ),
    sa.ForeignKeyConstraint(['user_index'], ['users.index'], ),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluations')
    # ### end Alembic commands ###
