"""empty message

Revision ID: 5310d50290ba
Revises: 1dccf760ef1a
Create Date: 2020-05-01 21:36:05.068682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5310d50290ba'
down_revision = '1dccf760ef1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('react_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'react_time')
    # ### end Alembic commands ###
