"""empty message

Revision ID: 5431644d97a0
Revises: 
Create Date: 2020-05-07 14:01:19.769197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5431644d97a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('users',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('slack_id', sa.String(length=80), nullable=True),
    sa.Column('intra_id', sa.String(length=80), nullable=True),
    sa.Column('register', sa.Boolean(), nullable=True),
    sa.Column('joined', sa.Boolean(), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('intra_id'),
    sa.UniqueConstraint('slack_id')
    )
    op.create_table('matches',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('match_day', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activity_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_index'], ['activities.index'], ),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('evaluations',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('send_time', sa.DateTime(), nullable=True),
    sa.Column('react_time', sa.DateTime(), nullable=True),
    sa.Column('match_index', sa.Integer(), nullable=True),
    sa.Column('user_index', sa.Integer(), nullable=True),
    sa.Column('mate_index', sa.Integer(), nullable=True),
    sa.Column('satisfaction', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_index'], ['matches.index'], ),
    sa.ForeignKeyConstraint(['mate_index'], ['users.index'], ),
    sa.ForeignKeyConstraint(['user_index'], ['users.index'], ),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('user_identifier',
    sa.Column('user_index', sa.Integer(), nullable=True),
    sa.Column('match_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_index'], ['matches.index'], ),
    sa.ForeignKeyConstraint(['user_index'], ['users.index'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_identifier')
    op.drop_table('evaluations')
    op.drop_table('matches')
    op.drop_table('users')
    op.drop_table('activities')
    # ### end Alembic commands ###
