"""empty message

Revision ID: a44f07721317
Revises: 
Create Date: 2020-04-24 20:31:44.001250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44f07721317'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('match_day', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('users',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('slack_id', sa.String(length=80), nullable=True),
    sa.Column('intra_id', sa.String(length=80), nullable=True),
    sa.Column('register', sa.Boolean(), nullable=True),
    sa.Column('joined', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('intra_id'),
    sa.UniqueConstraint('slack_id')
    )
    op.create_table('user_identifier',
    sa.Column('user_index', sa.Integer(), nullable=True),
    sa.Column('match_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_index'], ['matches.index'], ),
    sa.ForeignKeyConstraint(['user_index'], ['users.index'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_identifier')
    op.drop_table('users')
    op.drop_table('matches')
    # ### end Alembic commands ###
