"""empty message

Revision ID: f55bb5d4d09d
Revises: fee80b6a19d4
Create Date: 2020-05-03 22:46:39.931139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f55bb5d4d09d'
down_revision = 'fee80b6a19d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('activity_index', sa.Integer(), nullable=True))
    op.drop_constraint('matches_activity_fkey', 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'activities', ['activity_index'], ['index'])
    op.drop_column('matches', 'activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('activity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key('matches_activity_fkey', 'matches', 'activities', ['activity'], ['index'])
    op.drop_column('matches', 'activity_index')
    # ### end Alembic commands ###
